import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";



// Import Inter font from Google Fonts
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter", // Optional: Custom variable for the Inter font
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"], // Available weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body className={`${inter.variable} antialiased`}>
        <div>
          {children}
        </div>
      </body>
    </html>

  );
}
